# Generated by Django 4.2.4 on 2023-08-13 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputPage',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('input_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('placeholder', models.CharField(max_length=40)),
                ('coefficient', models.IntegerField()),
                ('constant', models.IntegerField()),
                ('input_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.inputpage')),
            ],
        ),
    ]
