# Generated by Django 4.2.4 on 2023-08-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_output_outputpage_remove_input_constant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputpage',
            name='description',
        ),
        migrations.AlterField(
            model_name='inputpage',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='outputpage',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
