# Generated by Django 4.2.4 on 2023-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_outputpage_description_alter_inputpage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputpage',
            name='description',
            field=models.TextField(default='this is a descr', max_length=100),
            preserve_default=False,
        ),
    ]
